source 'https://rubygems.org'

gem "rake"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-index"
gem "json"
gem "faker"
gem "shotgun"
gem "rakeup"
gem "rspec"
gem "mail"
gem "archive-tar-minitar"

gem "capybara"
gem "selenium-webdriver"
gem "cucumber"
gem "capybara-screenshot"
