
module Smail
end

require 'generator'
require 'smail/security_casing'
require 'smail/security_casing_examples'
require 'smail/stats'
require 'smail/stats_observer'
require 'smail/sorted_mail'
require 'smail/mail'
require 'smail/persona'
require 'smail/mail_service'
require 'smail/fake'
require 'smail/mailset'
require 'smail/server'
require 'smail/paginate'
require 'smail/all'
require 'smail/search'
require 'smail/tags'
require 'smail/combined_observer'
require 'smail/contacts_observer'
require 'smail/contact'
require 'smail/contacts'
require 'smail/contacts_sorter'
require 'smail/contacts_search'
require 'smail/mail_scope_filter'
