#!/bin/bash
#
# Copyright (c) 2014 ThoughtWorks, Inc.
#
# Pixelated is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pixelated is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Pixelated. If not, see <http://www.gnu.org/licenses/>.

PIXELATED_PATH=/var/lib/pixelated
. $PIXELATED_PATH/virtualenv/bin/activate
cd $PIXELATED_PATH/service/

$PIXELATED_PATH/virtualenv/bin/gunicorn user_agent:app -b 0.0.0.0:$USER_AGENT_PORT -D -p ~/.gunicorn.pid --log-file=~/.gunicorn.log
